[package]
name = "webpage"
description = "Small library to fetch info about a web page: title, description, language, HTTP info, RSS feeds, Opengraph, Schema.org, and more"
readme = "README.md"
keywords = ["webpage", "html", "opengraph"]
license = "MIT"
version = "1.1.0"
authors = ["Otto <otto@ot-to.nl>"]
repository = "https://github.com/orottier/webpage-rs"
edition = "2018"

[dependencies]
curl = "0.4.12"
html5ever = "0.22.3"
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = "1.0"
